<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class History extends Model
{

    public function set_old_data(  $value )
    {
        $this->old_data = json_encode( $value );
    }

    public function set_new_data( $value )
    {
        $this->new_data = json_encode( $value );
    }

    public function save( array $options = [ ] )
    {
        if(
            is_array( $this->old_data )
            && is_array( $this->new_data )
            && array_diff($this->old_data, $this->new_data )
        ) {
            $this->old_data = json_encode( $this->old_data );
            $this->new_data = json_encode( $this->new_data );
        }

        return parent::save($options); // TODO: Change the autogenerated stub
    }

}
